### Generic CI Template for chrootbuild
#
#
#  Usage: chrootbuild [options]
#
#     -b <branch> Branch to use:
#                 (unstable/testing/stable-staging/stable;
#                 arm-unstable/arm-testing/arm-stable)
#                 default: unstable / arm-unstable
#     -c          Start with clean chroot fs
#     -h          This help
#     -i <pkg>    Install package(s) to chroot fs
#                 (for multiple packages repeat -i flag)
#     -l <list>   List(s) to build
#                 (for multiple lists repeat -l flag)
#     -n          Install built pkg to chroot fs
#     -p <pkg>    Package(s) to build
#                 (for multiple packages repeat -p flag)
#     -r          Remove previously built packages in $PKGDEST
#     -s          Sign package(s)

before_script:
    - echo "$(nproc) CPUs on $(uname -a) in Docker..."
    - apt update
    - DEBIAN_FRONTEND=noninteractive apt -y install git build-essential cmake libarchive-dev pkg-config libcurl4-openssl-dev libgpgme-dev libssl-dev fakeroot dh-autoreconf libarchive-tools xsltproc gawk subversion
    - git clone https://gitlab.manjaro.org/manjaro-arm/packages/core/pacman.git
    - export pacver=5.2.2
    - export contribver=1.4.0
    - cd pacman
    - wget https://sources.archlinux.org/other/pacman/pacman-$pacver.tar.gz
    - wget https://git.archlinux.org/pacman-contrib.git/snapshot/pacman-contrib-$contribver.tar.gz
    - tar -xvf pacman-$pacver.tar.gz
    - tar -xvf pacman-contrib-$contribver.tar.gz
    - cd pacman-$pacver
    - patch -p1 -i ../pacman-sync-first-option.patch
    - cd ../pacman-$pacver
    - ./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var --disable-doc --with-scriptlet-shell=/usr/bin/bash --with-ldconfig=/usr/bin/ldconfig
    - make V=1
    - make install
    - install -m644 pacman.conf.aarch64 /etc/pacman.conf
    - install -m644 makepkg.conf /etc/
    - sed -i /etc/makepkg.conf -e "s|@CARCH[@]|aarch64|g" -e "s|@CHOST[@]|aarch64-pc-linux-gnu|g" -e "s|@CARCHFLAGS[@]|-march=armv8|g"
    - install -m644 etc-pacman.d-gnupg.mount /usr/lib/systemd/system/etc-pacman.d-gnupg.mount
    - install -m644 pacman-init.service /usr/lib/systemd/system/pacman-init.service
    - cd pacman-contrib-$contribver.tar.gz
    - ./autogen.sh
    - ./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var --disable-doc
    - make
    - make install

    - cd ..
    - git clone https://gitlab.manjaro.org/tools/development-tools/manjaro-chrootbuild
    - cd manjaro-chrootbuild
    - ./install.sh
    - echo "PKGDEST = </pkg/destination>" >> /etc/makepkg.conf
    - echo "PACKAGER = Manjaro Build Server <mnjobuild@manjaro.org>" >> /etc/makepkg.conf
    - echo "GPGKEY = <keyID>" >> /etc/makepkg.conf
    - pacman-key --init
    - cp /etc/chrootbuild/pacman.conf.aarch64 /etc/pacman.conf
    - sed -i "s/@BRANCH@/arm-unstable/g" /etc/pacman.conf
    - pacman -Sy manjaro-keyring archlinux-keyring
    - pacman-key --populate manjaro archlinux

package:
  tags:
    - aarch64
    - build-server
  script:
    # build pkg via chrootbuild
    - export PKG=${PWD##*/}
    - cd ..
    - chrootbuild -cp $PKG
    - mv -v ./*.pkg.tar.* $PKG
  artifacts:
    paths:
    - ./*.pkg.tar.*
    expire_in: 1 week
